INSERT INTO words (word, category, image_link) VALUES ('bear', 'Animals', '/resources/flashcards/Animals/bear.svg');
INSERT INTO words (word, category, image_link) VALUES ('bird', 'Animals', '/resources/flashcards/Animals/bird.svg');
INSERT INTO words (word, category, image_link) VALUES ('cat', 'Animals', '/resources/flashcards/Animals/cat.svg');
INSERT INTO words (word, category, image_link) VALUES ('cow', 'Animals', '/resources/flashcards/Animals/cow.svg');
INSERT INTO words (word, category, image_link) VALUES ('duck', 'Animals', '/resources/flashcards/Animals/duck.svg');
INSERT INTO words (word, category, image_link) VALUES ('elephant', 'Animals', '/resources/flashcards/Animals/elephant.svg');
INSERT INTO words (word, category, image_link) VALUES ('fish', 'Animals', '/resources/flashcards/Animals/fish.svg');
INSERT INTO words (word, category, image_link) VALUES ('horse', 'Animals', '/resources/flashcards/Animals/horse.svg');
INSERT INTO words (word, category, image_link) VALUES ('monkey', 'Animals', '/resources/flashcards/Animals/monkey.svg');
INSERT INTO words (word, category, image_link) VALUES ('pig', 'Animals', '/resources/flashcards/Animals/pig.svg');
INSERT INTO words (word, category, image_link) VALUES ('rabbit', 'Animals', '/resources/flashcards/Animals/rabbit.svg');
INSERT INTO words (word, category) VALUES ('bunny', 'Animals');
INSERT INTO words (word, category, image_link) VALUES ('sheep', 'Animals', '/resources/flashcards/Animals/sheep.svg');
INSERT INTO words (word, category, image_link) VALUES ('bathtub', 'Household', '/resources/flashcards/Household/bathtub.eps');
INSERT INTO words (word, category, image_link) VALUES ('chair', 'Household', '/resources/flashcards/Household/chair.svg');
INSERT INTO words (word, category, image_link) VALUES ('cup', 'Household', '/resources/flashcards/Household/cup.svg');
INSERT INTO words (word, category, image_link) VALUES ('door', 'Household', '/resources/flashcards/Household/door.eps');
INSERT INTO words (word, category, image_link) VALUES ('knife', 'Household', '/resources/flashcards/Household/knife.svg');
INSERT INTO words (word, category, image_link) VALUES ('phone', 'Household', '/resources/flashcards/Household/phone.svg');
INSERT INTO words (word, category) VALUES ('potty', 'Household');
INSERT INTO words (word, category) VALUES ('toilet', 'Household');
INSERT INTO words (word, category, image_link) VALUES ('spoon', 'Household', '/resources/flashcards/Household/spoon.svg');
INSERT INTO words (word, category, image_link) VALUES ('table', 'Household', '/resources/flashcards/Household/table.svg');
INSERT INTO words (word, category, image_link) VALUES ('toothbrush', 'Household', '/resources/flashcards/Household/toothbrush.svg');
INSERT INTO words (word, category, image_link) VALUES ('fork', 'Household', '/resources/flashcards/Household/fork.svg');
INSERT INTO words (word, category, image_link) VALUES ('ear', 'Body Parts', '/resources/flashcards/BodyParts/ear.svg');
INSERT INTO words (word, category, image_link) VALUES ('eyes', 'Body Parts', '/resources/flashcards/BodyParts/eyes.svg');
INSERT INTO words (word, category, image_link) VALUES ('foot', 'Body Parts', '/resources/flashcards/BodyParts/foot.svg');
INSERT INTO words (word, category, image_link) VALUES ('hair', 'Body Parts', '/resources/flashcards/BodyParts/hair.svg');
INSERT INTO words (word, category, image_link) VALUES ('hand', 'Body Parts', '/resources/flashcards/BodyParts/hand.svg');
INSERT INTO words (word, category, image_link) VALUES ('mouth', 'Body Parts', '/resources/flashcards/BodyParts/mouth.svg');
INSERT INTO words (word, category, image_link) VALUES ('nose', 'Body Parts', '/resources/flashcards/BodyParts/nose.svg');
INSERT INTO words (word, category, image_link) VALUES ('teeth', 'Body Parts', '/resources/flashcards/BodyParts/teeth.svg');
INSERT INTO words (word, category, image_link) VALUES ('ears', 'Body Parts', '/resources/flashcards/BodyParts/ears.svg');
INSERT INTO words (word, category) VALUES ('feet', 'Body Parts');
INSERT INTO words (word, category) VALUES ('boot', 'Clothes');
INSERT INTO words (word, category, image_link) VALUES ('boots', 'Clothes', '/resources/flashcards/Clothes/boots.svg');
INSERT INTO words (word, category, image_link) VALUES ('coat', 'Clothes', '/resources/flashcards/Clothes/coat.svg');
INSERT INTO words (word, category, image_link) VALUES ('diaper', 'Clothes', '/resources/flashcards/Clothes/diaper.svg');
INSERT INTO words (word, category, image_link) VALUES ('hat', 'Clothes', '/resources/flashcards/Clothes/hat.svg');
INSERT INTO words (word, category, image_link) VALUES ('pants', 'Clothes', '/resources/flashcards/Clothes/pants.svg');
INSERT INTO words (word, category, image_link) VALUES ('shirt', 'Clothes', '/resources/flashcards/Clothes/shirt.svg');
INSERT INTO words (word, category) VALUES ('shoe', 'Clothes');
INSERT INTO words (word, category, image_link) VALUES ('shoes', 'Clothes', '/resources/flashcards/Clothes/shoes.svg');
INSERT INTO words (word, category) VALUES ('sock', 'Clothes');
INSERT INTO words (word, category, image_link) VALUES ('socks', 'Clothes', '/resources/flashcards/Clothes/socks.svg');
INSERT INTO words (word, category, image_link) VALUES ('jacket', 'Clothes', '/resources/flashcards/Clothes/jacket.svg');
INSERT INTO words (word, category, image_link) VALUES ('flower', 'Nature', '/resources/flashcards/Nature/flower.svg');
INSERT INTO words (word, category, image_link) VALUES ('rain', 'Nature', '/resources/flashcards/Nature/rain.svg');
INSERT INTO words (word, category, image_link) VALUES ('sun', 'Nature', '/resources/flashcards/Nature/sun.svg');
INSERT INTO words (word, category, image_link) VALUES ('tree', 'Nature', '/resources/flashcards/Nature/tree.svg');
INSERT INTO words (word, category, image_link) VALUES ('moon', 'Nature', '/resources/flashcards/Nature/moon.svg');
INSERT INTO words (word, category, image_link) VALUES ('baby', 'People', '/resources/flashcards/People/baby.svg');
INSERT INTO words (word, category, image_link) VALUES ('boy', 'People', '/resources/flashcards/People/boy-girl.svg');
INSERT INTO words (word, category) VALUES ('Daddy', 'People');
INSERT INTO words (word, category, image_link) VALUES ('girl', 'People', '/resources/flashcards/People/boy-girl.svg');
INSERT INTO words (word, category) VALUES ('Mommy', 'People');
INSERT INTO words (word, category, image_link) VALUES ('dad', 'People', '/resources/flashcards/People/dad-mom.svg');
INSERT INTO words (word, category, image_link) VALUES ('mom', 'People', '/resources/flashcards/People/dad-mom.svg');
INSERT INTO words (word, category, image_link) VALUES ('apple', 'Food', '/resources/flashcards/Food/apple.svg');
INSERT INTO words (word, category, image_link) VALUES ('banana', 'Food', '/resources/flashcards/Food/banana.svg');
INSERT INTO words (word, category, image_link) VALUES ('candy', 'Food', '/resources/flashcards/Food/candy.svg');
INSERT INTO words (word, category, image_link) VALUES ('cheese', 'Food', '/resources/flashcards/Food/cheese.svg');
INSERT INTO words (word, category, image_link) VALUES ('cookie', 'Food', '/resources/flashcards/Food/cookie.svg');
INSERT INTO words (word, category, image_link) VALUES ('cracker', 'Food', '/resources/flashcards/Food/cracker.svg');
INSERT INTO words (word, category, image_link) VALUES ('French fries', 'Food', '/resources/flashcards/Food/frenchfries.svg');
INSERT INTO words (word, category, image_link) VALUES ('hamburger', 'Food', '/resources/flashcards/Food/hamburger.svg');
INSERT INTO words (word, category, image_link) VALUES ('hotdog', 'Food', '/resources/flashcards/Household/hotdog.svg');
INSERT INTO words (word, category) VALUES ('ice cream cone', 'Food');
INSERT INTO words (word, category, image_link) VALUES ('juice', 'Food', '/resources/flashcards/Food/juice.svg');
INSERT INTO words (word, category, image_link) VALUES ('milk', 'Food', '/resources/flashcards/Food/milk.svg');
INSERT INTO words (word, category, image_link) VALUES ('pizza', 'Food', '/resources/flashcards/Food/pizza.svg');
INSERT INTO words (word, category, image_link) VALUES ('strawberry', 'Food', '/resources/flashcards/Food/strawberry.svg');
INSERT INTO words (word, category, image_link) VALUES ('water', 'Food', '/resources/flashcards/Food/water.svg');
INSERT INTO words (word, category) VALUES ('airplane', 'Toys/Travel');
INSERT INTO words (word, category, image_link) VALUES ('ball', 'Toys/Travel', '/resources/flashcards/ToysTravel/ball.svg');
INSERT INTO words (word, category, image_link) VALUES ('balloon', 'Toys/Travel', '/resources/flashcards/ToysTravel/balloon.svg');
INSERT INTO words (word, category, image_link) VALUES ('bike', 'Toys/Travel', '/resources/flashcards/ToysTravel/bike.svg');
INSERT INTO words (word, category, image_link) VALUES ('book', 'Toys/Travel', '/resources/flashcards/ToysTravel/book.svg');
INSERT INTO words (word, category, image_link) VALUES ('bubbles', 'Toys/Travel', '/resources/flashcards/ToysTravel/bubbles.eps');
INSERT INTO words (word, category, image_link) VALUES ('car', 'Toys/Travel', '/resources/flashcards/ToysTravel/car.svg');
INSERT INTO words (word, category, image_link) VALUES ('train', 'Toys/Travel', '/resources/flashcards/ToysTravel/train.svg');
INSERT INTO words (word, category, image_link) VALUES ('plane', 'Toys/Travel', '/resources/flashcards/ToysTravel/plane.svg');
INSERT INTO words (word, category, image_link) VALUES ('blow', 'Action Words/Verbs', '/resources/flashcards/Verbs/blow.svg');
INSERT INTO words (word, category) VALUES ('clap', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('cry', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('cut', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('drink', 'Action Words/Verbs');
INSERT INTO words (word, category, image_link) VALUES ('drive', 'Action Words/Verbs', '/resources/flashcards/Verbs/drive.svg');
INSERT INTO words (word, category) VALUES ('drop', 'Action Words/Verbs');
INSERT INTO words (word, category, image_link) VALUES ('eat', 'Action Words/Verbs', '/resources/flashcards/Verbs/eat.svg');
INSERT INTO words (word, category) VALUES ('fall down', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('hug', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('jump', 'Action Words/Verbs');
INSERT INTO words (word, category, image_link) VALUES ('kick', 'Action Words/Verbs', '/resources/flashcards/Verbs/kick.svg');
INSERT INTO words (word, category, image_link) VALUES ('kiss', 'Action Words/Verbs', '/resources/flashcards/Verbs/kiss.svg');
INSERT INTO words (word, category) VALUES ('open', 'Action Words/Verbs');
INSERT INTO words (word, category, image_link) VALUES ('pour', 'Action Words/Verbs', '/resources/flashcards/Verbs/pour.svg');
INSERT INTO words (word, category, image_link) VALUES ('push', 'Action Words/Verbs', '/resources/flashcards/Verbs/push.svg');
INSERT INTO words (word, category, image_link) VALUES ('run', 'Action Words/Verbs', '/resources/flashcards/Verbs/run.svg');
INSERT INTO words (word, category) VALUES ('sit down', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('sleep', 'Action Words/Verbs');
INSERT INTO words (word, category, image_link) VALUES ('stir', 'Action Words/Verbs', '/resources/flashcards/Verbs/stir.svg');
INSERT INTO words (word, category, image_link) VALUES ('throw', 'Action Words/Verbs', '/resources/flashcards/Verbs/throw.svg');
INSERT INTO words (word, category) VALUES ('turn around', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('walk', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('wash', 'Action Words/Verbs');
INSERT INTO words (word, category, image_link) VALUES ('blue', 'Adjectives', '/resources/flashcards/Adjectives/color-blue.svg');
INSERT INTO words (word, category, image_link) VALUES ('green', 'Adjectives', '/resources/flashcards/Adjectives/color-green.svg');
INSERT INTO words (word, category, image_link) VALUES ('orange', 'Adjectives', '/resources/flashcards/Adjectives/color-orange.svg');
INSERT INTO words (word, category, image_link) VALUES ('purple', 'Adjectives', '/resources/flashcards/Adjectives/color-purple.svg');
INSERT INTO words (word, category, image_link) VALUES ('red', 'Adjectives', '/resources/flashcards/Adjectives/color-red.svg');
INSERT INTO words (word, category, image_link) VALUES ('yellow', 'Adjectives', '/resources/flashcards/Adjectives/color-yellow.svg');
INSERT INTO words (word, category) VALUES ('one', 'Adjectives');
INSERT INTO words (word, category) VALUES ('two', 'Adjectives');
INSERT INTO words (word, category) VALUES ('three', 'Adjectives');
INSERT INTO words (word, category, image_link) VALUES ('big', 'Adjectives', '/resources/flashcards/Adjectives/big-little.svg');
INSERT INTO words (word, category, image_link) VALUES ('little', 'Adjectives', '/resources/flashcards/Adjectives/big-little.svg');
INSERT INTO words (word, category, image_link) VALUES ('clean', 'Adjectives', '/resources/flashcards/Adjectives/clean.svg');
INSERT INTO words (word, category, image_link) VALUES ('dirty', 'Adjectives', '/resources/flashcards/Adjectives/dirty.svg');
INSERT INTO words (word, category, image_link) VALUES ('happy', 'Adjectives', '/resources/flashcards/Adjectives/happy.svg');
INSERT INTO words (word, category, image_link) VALUES ('sad', 'Adjectives', '/resources/flashcards/Adjectives/sad.svg');
INSERT INTO words (word, category, image_link) VALUES ('hot', 'Adjectives', '/resources/flashcards/Adjectives/hot.svg');
INSERT INTO words (word, category, image_link) VALUES ('cold', 'Adjectives', '/resources/flashcards/Adjectives/cold.svg');