INSERT INTO words (word, category, image_link) VALUES ('bear', 'Animals', '/home/user/Github/manuscope/manuscope/frontend/resources/flashcards/Animals/bear.svg');
INSERT INTO words (word, category, image_link) VALUES ('bird', 'Animals', '/home/user/Github/manuscope/frontend/resources/flashcards/Animals/bird.svg');
INSERT INTO words (word, category, image_link) VALUES ('cat', 'Animals', '/home/user/Github/manuscope/frontend/resources/flashcards/Animals/cat.svg');
INSERT INTO words (word, category, image_link) VALUES ('cow', 'Animals', '/home/user/Github/manuscope/frontend/resources/flashcards/Animals/cow.svg');
INSERT INTO words (word, category, image_link) VALUES ('dog', 'Animals', '/home/user/Github/manuscope/frontend/resources/flashcards/Animals/dog.svg');
INSERT INTO words (word, category, image_link) VALUES ('duck', 'Animals', '/home/user/Github/manuscope/frontend/resources/flashcards/Animals/duck.svg');
INSERT INTO words (word, category, image_link) VALUES ('elephant', 'Animals', '/home/user/Github/manuscope/frontend/resources/flashcards/Animals/elephant.svg');
INSERT INTO words (word, category, image_link) VALUES ('fish', 'Animals', '/home/user/Github/manuscope/frontend/resources/flashcards/Animals/fish.svg');
INSERT INTO words (word, category, image_link) VALUES ('horse', 'Animals', '/home/user/Github/manuscope/frontend/resources/flashcards/Animals/horse.svg');
INSERT INTO words (word, category, image_link) VALUES ('monkey', 'Animals', '/home/user/Github/manuscope/frontend/resources/flashcards/Animals/monkey.svg');
INSERT INTO words (word, category, image_link) VALUES ('pig', 'Animals', '/home/user/Github/manuscope/frontend/resources/flashcards/Animals/pig.svg');
INSERT INTO words (word, category, image_link) VALUES ('rabbit/bunny', 'Animals', '/home/user/Github/manuscope/frontend/resources/flashcards/Animals/rabbit.svg');
INSERT INTO words (word, category, image_link) VALUES ('sheep', 'Animals', '/home/user/Github/manuscope/frontend/resources/flashcards/Animals/sheep.svg');
INSERT INTO words (word, category) VALUES ('bathtub', 'Household');
INSERT INTO words (word, category, image_link) VALUES ('chair', 'Household', '/home/user/Github/manuscope/frontend/resources/flashcards/Household/chair.svg');
INSERT INTO words (word, category, image_link) VALUES ('cup', 'Household', '/home/user/Github/manuscope/frontend/resources/flashcards/Household/cup.svg');
INSERT INTO words (word, category) VALUES ('door', 'Household');
INSERT INTO words (word, category, image_link) VALUES ('knife', 'Household', '/home/user/Github/manuscope/frontend/resources/flashcards/Household/knife.svg');
INSERT INTO words (word, category, image_link) VALUES ('phone', 'Household', '/home/user/Github/manuscope/frontend/resources/flashcards/Household/phone.svg');
INSERT INTO words (word, category, image_link) VALUES ('potty/toilet', 'Household', '/home/user/Github/manuscope/frontend/resources/flashcards/Household/potty.svg');
INSERT INTO words (word, category, image_link) VALUES ('spoon', 'Household', '/home/user/Github/manuscope/frontend/resources/flashcards/Household/spoon.svg');
INSERT INTO words (word, category, image_link) VALUES ('table', 'Household', '/home/user/Github/manuscope/frontend/resources/flashcards/Household/table.svg');
INSERT INTO words (word, category, image_link) VALUES ('toothbrush', 'Household', '/home/user/Github/manuscope/frontend/resources/flashcards/Household/toothbrush.svg');
INSERT INTO words (word, category) VALUES ('ear', 'Body Parts');
INSERT INTO words (word, category, image_link) VALUES ('eyes', 'Body Parts', '/home/user/Github/manuscope/frontend/resources/flashcards/BodyParts/eyes.svg');
INSERT INTO words (word, category) VALUES ('foot', 'Body Parts');
INSERT INTO words (word, category, image_link) VALUES ('hair', 'Body Parts', '/home/user/Github/manuscope/frontend/resources/flashcards/BodyParts/hair.svg');
INSERT INTO words (word, category, image_link) VALUES ('hand', 'Body Parts', '/home/user/Github/manuscope/frontend/resources/flashcards/BodyParts/hand.svg');
INSERT INTO words (word, category, image_link) VALUES ('mouth', 'Body Parts', '/home/user/Github/manuscope/frontend/resources/flashcards/BodyParts/mouth.svg');
INSERT INTO words (word, category, image_link) VALUES ('nose', 'Body Parts', '/home/user/Github/manuscope/frontend/resources/flashcards/BodyParts/nose.svg');
INSERT INTO words (word, category, image_link) VALUES ('teeth', 'Body Parts', '/home/user/Github/manuscope/frontend/resources/flashcards/BodyParts/teeth.svg');
INSERT INTO words (word, category, image_link) VALUES ('boot/s', 'Clothes', '/home/user/Github/manuscope/frontend/resources/flashcards/Clothes/boots.svg');
INSERT INTO words (word, category) VALUES ('coat', 'Clothes');
INSERT INTO words (word, category, image_link) VALUES ('diaper', 'Clothes', '/home/user/Github/manuscope/frontend/resources/flashcards/Clothes/diaper.svg');
INSERT INTO words (word, category, image_link) VALUES ('hat', 'Clothes', '/home/user/Github/manuscope/frontend/resources/flashcards/Clothes/hat.svg');
INSERT INTO words (word, category, image_link) VALUES ('pants', 'Clothes', '/home/user/Github/manuscope/frontend/resources/flashcards/Clothes/pants.svg');
INSERT INTO words (word, category, image_link) VALUES ('shirt', 'Clothes', '/home/user/Github/manuscope/frontend/resources/flashcards/Clothes/shirt.svg');
INSERT INTO words (word, category, image_link) VALUES ('shoe/s', 'Clothes', '/home/user/Github/manuscope/frontend/resources/flashcards/Clothes/shoes.svg');
INSERT INTO words (word, category, image_link) VALUES ('sock/s', 'Clothes', '/home/user/Github/manuscope/frontend/resources/flashcards/Clothes//socks.svg');
INSERT INTO words (word, category, image_link) VALUES ('flower', 'Nature', '/home/user/Github/manuscope/frontend/resources/flashcards/Nature/flower.svg');
INSERT INTO words (word, category, image_link) VALUES ('rain', 'Nature', '/home/user/Github/manuscope/frontend/resources/flashcards/Nature/rain.svg');
INSERT INTO words (word, category, image_link) VALUES ('sun', 'Nature', '/home/user/Github/manuscope/frontend/resources/flashcards/Nature/sun.svg');
INSERT INTO words (word, category, image_link) VALUES ('tree', 'Nature', '/home/user/Github/manuscope/frontend/resources/flashcards/Nature/tree.svg');
INSERT INTO words (word, category, image_link) VALUES ('baby', 'People', '/home/user/Github/manuscope/frontend/resources/flashcards/People/baby.svg');
INSERT INTO words (word, category, image_link) VALUES ('boy', 'People', '/home/user/Github/manuscope/frontend/resources/flashcards/People/boy-girl.svg');
INSERT INTO words (word, category, image_link) VALUES ('Daddy', 'People', '/home/user/Github/manuscope/frontend/resources/flashcards/People/dad-mom.svg');
INSERT INTO words (word, category, image_link) VALUES ('girl', 'People', '/home/user/Github/manuscope/frontend/resources/flashcards/People/boy-girl.svg');
INSERT INTO words (word, category, image_link) VALUES ('Mommy', 'People', '/home/user/Github/manuscope/frontend/resources/flashcards/People/dad-mom.svg');
INSERT INTO words (word, category, image_link) VALUES ('apple', 'Food', '/home/user/Github/manuscope/frontend/resources/flashcards/Food/apple.svg');
INSERT INTO words (word, category, image_link) VALUES ('banana', 'Food', '/home/user/Github/manuscope/frontend/resources/flashcards/Food/banana.svg');
INSERT INTO words (word, category, image_link) VALUES ('candy', 'Food', '/home/user/Github/manuscope/frontend/resources/flashcards/Food/candy.svg');
INSERT INTO words (word, category, image_link) VALUES ('cheese', 'Food', '/home/user/Github/manuscope/frontend/resources/flashcards/Food/cheese.svg');
INSERT INTO words (word, category, image_link) VALUES ('cookie', 'Food', '/home/user/Github/manuscope/frontend/resources/flashcards/Food/cookie.svg');
INSERT INTO words (word, category, image_link) VALUES ('cracker', 'Food', '/home/user/Github/manuscope/frontend/resources/flashcards/Food/cracker.svg');
INSERT INTO words (word, category, image_link) VALUES ('French fries', 'Food', '/home/user/Github/manuscope/frontend/resources/flashcards/Food/frenchfries.svg');
INSERT INTO words (word, category, image_link) VALUES ('hamburger', 'Food', '/home/user/Github/manuscope/frontend/resources/flashcards/Food/hamburger.svg');
INSERT INTO words (word, category, image_link) VALUES ('hotdog', 'Food', '/home/user/Github/manuscope/frontend/resources/flashcards/Food/hotdog.svg');
INSERT INTO words (word, category, image_link) VALUES ('ice cream cone', 'Food', '/home/user/Github/manuscope/frontend/resources/flashcards/Food/icecream.svg');
INSERT INTO words (word, category, image_link) VALUES ('juice', 'Food', '/home/user/Github/manuscope/frontend/resources/flashcards/Food/juice.svg');
INSERT INTO words (word, category, image_link) VALUES ('milk', 'Food', '/home/user/Github/manuscope/frontend/resources/flashcards/Food/milk.svg');
INSERT INTO words (word, category, image_link) VALUES ('pizza', 'Food', '/home/user/Github/manuscope/frontend/resources/flashcards/Food/pizza.svg');
INSERT INTO words (word, category, image_link) VALUES ('strawberry', 'Food', '/home/user/Github/manuscope/frontend/resources/flashcards/Food/strawberry.svg');
INSERT INTO words (word, category, image_link) VALUES ('water', 'Food', '/home/user/Github/manuscope/frontend/resources/flashcards/Food/water.svg');
INSERT INTO words (word, category, image_link) VALUES ('airplane', 'Toys/Travel', '/home/user/Github/manuscope/frontend/resources/flashcards/ToysTravel/plane.svg');
INSERT INTO words (word, category, image_link) VALUES ('ball', 'Toys/Travel', '/home/user/Github/manuscope/frontend/resources/flashcards/ToysTravel/ball.svg');
INSERT INTO words (word, category, image_link) VALUES ('balloon', 'Toys/Travel', '/home/user/Github/manuscope/frontend/resources/flashcards/ToysTravel/balloon.svg');
INSERT INTO words (word, category, image_link) VALUES ('bike', 'Toys/Travel', '/home/user/Github/manuscope/frontend/resources/flashcards/ToysTravel/bike.svg');
INSERT INTO words (word, category, image_link) VALUES ('book', 'Toys/Travel', '/home/user/Github/manuscope/frontend/resources/flashcards/ToysTravel/book.svg');
INSERT INTO words (word, category) VALUES ('bubbles', 'Toys/Travel');
INSERT INTO words (word, category, image_link) VALUES ('car', 'Toys/Travel', '/home/user/Github/manuscope/frontend/resources/flashcards/ToysTravel/car.svg');
INSERT INTO words (word, category, image_link) VALUES ('train', 'Toys/Travel', '/home/user/Github/manuscope/frontend/resources/flashcards/ToysTravel/train.svg');
INSERT INTO words (word, category) VALUES ('blow', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('clap', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('cry', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('cut', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('drink', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('drive', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('drop', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('eat', 'Action Words/Verbs');
INSERT INTO words (word, category, image_link) VALUES ('fall down', 'Action Words/Verbs', '/home/user/Github/manuscope/frontend/resources/flashcards/ActionWordsVerbs/falldown.svg');
INSERT INTO words (word, category) VALUES ('hug', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('jump', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('kick', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('kiss', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('open', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('pour', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('push', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('run', 'Action Words/Verbs');
INSERT INTO words (word, category, image_link) VALUES ('sit down', 'Action Words/Verbs', '/home/user/Github/manuscope/frontend/resources/flashcards/ActionWordsVerbs/sitdown.svg');
INSERT INTO words (word, category) VALUES ('sleep', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('stir', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('throw', 'Action Words/Verbs');
INSERT INTO words (word, category, image_link) VALUES ('turn around', 'Action Words/Verbs', '/home/user/Github/manuscope/frontend/resources/flashcards/ActionWordsVerbs/turnaround.svg');
INSERT INTO words (word, category) VALUES ('walk', 'Action Words/Verbs');
INSERT INTO words (word, category) VALUES ('wash', 'Action Words/Verbs');
INSERT INTO words (word, category, image_link) VALUES ('blue', 'Adjectives', '/home/user/Github/manuscope/frontend/resources/flashcards/Adjectives/color-blue.svg');
INSERT INTO words (word, category, image_link) VALUES ('green', 'Adjectives', '/home/user/Github/manuscope/frontend/resources/flashcards/Adjectives/color-green.svg');
INSERT INTO words (word, category, image_link) VALUES ('orange', 'Adjectives', '/home/user/Github/manuscope/frontend/resources/flashcards/Adjectives/color-orange.svg');
INSERT INTO words (word, category, image_link) VALUES ('purple', 'Adjectives', '/home/user/Github/manuscope/frontend/resources/flashcards/Adjectives/color-purple.svg');
INSERT INTO words (word, category, image_link) VALUES ('red', 'Adjectives', '/home/user/Github/manuscope/frontend/resources/flashcards/Adjectives/color-red.svg');
INSERT INTO words (word, category, image_link) VALUES ('yellow', 'Adjectives', '/home/user/Github/manuscope/frontend/resources/flashcards/Adjectives/color-yellow.svg');
INSERT INTO words (word, category, image_link) VALUES ('one', 'Adjectives', '/home/user/Github/manuscope/frontend/resources/flashcards/Adjectives/number-1.svg');
INSERT INTO words (word, category, image_link) VALUES ('two', 'Adjectives', '/home/user/Github/manuscope/frontend/resources/flashcards/Adjectives/number-2.svg');
INSERT INTO words (word, category, image_link) VALUES ('three', 'Adjectives', '/home/user/Github/manuscope/frontend/resources/flashcards/Adjectives/number-3.svg');
INSERT INTO words (word, category, image_link) VALUES ('big/little', 'Adjectives', '/home/user/Github/manuscope/frontend/resources/flashcards/Adjectives/big-little.svg');
INSERT INTO words (word, category) VALUES ('clean/dirty', 'Adjectives');
INSERT INTO words (word, category) VALUES ('happy/sad', 'Adjectives');
INSERT INTO words (word, category) VALUES ('hot/cold', 'Adjectives');